### REQUESTS FOR USERS



### GET request to get all URLS:
GET http://localhost:8080/users
Authorization: Basic {{usernameAdmin1}} {{passwordAdmin1}}

###



### GET request to get a single User based on its ID:
GET http://localhost:8080/users/4
Authorization: Basic {{usernameAdmin1}} {{passwordAdmin1}}

###




### DELETE request to delete a single User based on its ID:
DELETE http://localhost:8080/users/1
Authorization: Basic {{usernameAdmin1}} {{usernameAdmin1}}

###



### POST request to add a single User:
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "something",
  "password": "ewqe",
  "email": "something@hotmail.com",
  "role": "USER"

}
###




