### REQUESTS FOR USERS



### GET request to get all URLS:
GET http://localhost:8080/users
Authorization: Basic {{usernameAdmin1}} {{passwordAdmin1}}
###



### GET request to get a single User based on its ID:
GET http://localhost:8080/users/4
Authorization: Basic {{usernameAdmin1}} {{passwordAdmin1}}


###




### DELETE request to delete a single User based on its ID:
DELETE http://localhost:8080/users/21
Authorization: Basic {{usernameUser2}} {{passwordUser2}}


###



### POST request to add a single User:
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "314",
  "password": "314",
  "email": "314@gmail.com"
}
###

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}

###



