### REQUESTS FOR USERS



### GET request to get all URLS:
GET http://localhost:8080/users
Authorization: Basic {{usernameAdmin1}} {{passwordAdmin1}}

###



### GET request to get a single User based on its ID:
GET http://localhost:8080/users/4
Authorization: Basic {{usernameAdmin1}} {{passwordAdmin1}}


###




### DELETE request to delete a single User based on its ID:
DELETE http://localhost:8080/users/82
Authorization: Basic {{tester}} {{testerPass}}


###



### POST request to add a single User:
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "testingCleanUp",
  "password": "testingCleanUp",
  "email": "testingCleanUp@gmail.com",
  "role": "USER"
}
###


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "testingCleanUp",
    "password": "testingCleanUp"
}

###



### PUT request to edit a single User based on its ID:
PATCH http://localhost:8080/users/edit/83
Content-Type: application/json
Authorization: Basic {{usernameAdmin1}} {{passwordAdmin1}}

{
  "username": "testingCleanUp",
  "password": "testingCleanUp",
  "email": "testingCleanUp@gmail.com",
  "role": "USER",
  "enabled": true
}

###
