### REQUESTS


### GET request to get all URLS:
GET http://localhost:8080/urls

###

### GET request to get a single URL based on the unique ID:
GET http://localhost:8080/urls/200

###

### GET request to read URLs health: checked
GET http://localhost:8080/urls/53/health

###

### GET request to get all URL names: checked
GET http://localhost:8080/urls/names

###

### DELETE request to delete a single URL by its id:
DELETE http://localhost:8080/urls/75

###

### POST request to write inside database, hardcoded:
POST http://localhost:8080/urls
Content-Type: application/json

{
  "addedByUserId": "1",
  "urlName": "YouTube",
  "fullUrl": "https://www.youtube.com"
}

###


### PATCH request to check and update all of the url healths
PATCH http://localhost:8080/urls/checkHealthAll


###




### GET request to get all URLS: checked
DELETE http://localhost:8080/urls

###


### PUT request to update a single URL based on its ID:
PUT http://localhost:8080/urls/81
Content-Type: application/json

{
  "urlName": "something",
  "fullUrl": "https://github.com"
}

###