

### GET request to get all URLS:
GET http://localhost:8080/url

###


### GET request to get a single URL based on the unique ID:
GET http://localhost:8080/url/5

###

### GET request to get all URL names:
GET http://localhost:8080/url/names

###



### DELETE request to delete a single URL by its id:
DELETE http://localhost:8080/url/5

###


### POST request to write inside database, hardcoded.
POST http://localhost:8080/url
Content-Type: application/json

{
  "urlid": 14,
  "addedbyuserid": "1",
  "urlname": "Url14",
  "fullurl": "https://medium.com/@abhinavv.singh/building-restful-apis-with-spring-boot-a-step-by-step-tutorial-with-detailed-code-e7e3372ae756",
  "urlhealth": "false"
}

###

